language: python
python: 3.6
install: 
  - pip install -r requirements.txt
script: 
  - python run.py
  - pytest
sudo: required
addons:
  chrome: beta

# before_install:
#   - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
#   ⋮